from __future__ import annotations

from pathlib import Path

from ivo.environment import OptionalDependencyStatus, collect_optional_model_dependencies


def build_model_setup_script(model_root: Path | str = Path("models"), stage: str | None = None) -> str:
    """Build a PowerShell setup script for recommended local model dependencies."""
    dependencies = [
        dependency
        for dependency in collect_optional_model_dependencies(model_root)
        if stage is None or dependency.stage == stage
    ]
    lines = [
        "$ErrorActionPreference = \"Stop\"",
        "",
        "# Generated by Intelligent Voice Over.",
        "# 确认模型许可证后再下载或使用；不同模型许可证独立于本项目代码许可证。",
        "# 不要提交 models/、真实视频、生成音频、API key、HF_TOKEN 或其他密钥到 Git。",
        "# 如需访问 Hugging Face 受限模型，请先运行 huggingface-cli login；不要把 token 写入脚本。",
        "# Do not commit model weights, API tokens, HF_TOKEN, or generated media to Git.",
        "# Review each model license before commercial use or redistribution.",
        "",
    ]
    if not dependencies:
        lines.append(f"# No recommended model dependencies matched stage: {stage}")
        return "\n".join(lines) + "\n"

    for dependency in dependencies:
        lines.extend(_render_dependency_setup_block(dependency))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_setup_script(
    output_path: Path,
    *,
    models_dir: Path | str = Path("models"),
    stage: str | None = None,
) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_model_setup_script(models_dir, stage=stage), encoding="utf-8")
    return output_path


def _render_dependency_setup_block(dependency: OptionalDependencyStatus) -> list[str]:
    lines = [
        f"# {dependency.stage} / {dependency.name}",
        _install_line(dependency.install_hint),
        f"New-Item -ItemType Directory -Force -Path {_ps_quote(dependency.model_dir)} | Out-Null",
        _download_line(dependency.download_hint, dependency.model_dir),
        f"# License: {dependency.license_hint}",
        f"# Verify: {dependency.verify_hint}",
    ]
    return lines


def _install_line(install_hint: str) -> str:
    if install_hint.startswith("uv pip install "):
        return install_hint
    return f"# Manual install: {install_hint}"


def _download_line(download_hint: str, model_dir: Path) -> str:
    local_dir_option = " --local-dir "
    if download_hint.startswith("huggingface-cli download ") and local_dir_option in download_hint:
        command, _separator, _old_dir = download_hint.partition(local_dir_option)
        return f"{command}{local_dir_option}{_ps_quote(model_dir)}"
    if download_hint.startswith("huggingface-cli download "):
        return f"{download_hint}{local_dir_option}{_ps_quote(model_dir)}"
    return f"# Download: {download_hint}"


def _ps_quote(path: Path) -> str:
    return "'" + str(path).replace("'", "''") + "'"
