$ErrorActionPreference = "Stop"

# Generated by Intelligent Voice Over.
# Do not commit model weights, API tokens, HF_TOKEN, or generated media to Git.
# Review each model license before commercial use or redistribution.

# asr / faster-whisper
uv pip install faster-whisper
New-Item -ItemType Directory -Force -Path 'models\asr\faster-whisper-large-v3' | Out-Null
huggingface-cli download Systran/faster-whisper-large-v3 --local-dir 'models\asr\faster-whisper-large-v3'
# License: MIT package; confirm the selected Whisper checkpoint license.
# Verify: uv run python examples/local_commands/faster_whisper_asr.py --help

# separation / demucs
uv pip install demucs
New-Item -ItemType Directory -Force -Path 'models\separation\demucs' | Out-Null
# Download: Demucs downloads named checkpoints on first use.
# License: MIT; confirm checkpoint terms before distribution.
# Verify: uv run python examples/local_commands/demucs_separate.py --help

# diarization / pyannote.audio
uv pip install pyannote.audio
New-Item -ItemType Directory -Force -Path 'models\diarization\pyannote-community-1' | Out-Null
huggingface-cli download pyannote/speaker-diarization-community-1 --local-dir 'models\diarization\pyannote-community-1'
# License: Requires Hugging Face login and accepted model terms; keep HF_TOKEN out of Git.
# Verify: uv run python examples/local_commands/pyannote_diarization.py --help

# tts / CosyVoice
# Manual install: install CosyVoice from https://github.com/FunAudioLLM/CosyVoice
New-Item -ItemType Directory -Force -Path 'models\tts\Fun-CosyVoice3-0.5B' | Out-Null
huggingface-cli download FunAudioLLM/Fun-CosyVoice3-0.5B-2512 --local-dir 'models\tts\Fun-CosyVoice3-0.5B'
# License: Fun-CosyVoice3 model card currently lists Apache-2.0; re-check before use.
# Verify: uv run python examples/local_commands/cosyvoice_tts.py --help

# tts / f5_tts
# Manual install: install the F5-TTS package matching your chosen checkpoint and script
New-Item -ItemType Directory -Force -Path 'models\tts\F5-TTS' | Out-Null
huggingface-cli download SWivid/F5-TTS --local-dir 'models\tts\F5-TTS'
# License: Code is MIT; pretrained checkpoints are CC-BY-NC.
# Verify: uv run python examples/local_commands/f5_tts_command.py --help

# translation / Qwen local LLM
uv pip install transformers accelerate
New-Item -ItemType Directory -Force -Path 'models\llm\Qwen3-8B' | Out-Null
huggingface-cli download Qwen/Qwen3-8B --local-dir 'models\llm\Qwen3-8B'
# License: Confirm the selected Qwen model license before redistribution or commercial use.
# Verify: Run Qwen through vLLM/SGLang/OpenAI-compatible HTTP profile first.

# translation / vLLM
uv pip install vllm
New-Item -ItemType Directory -Force -Path 'models\llm\Qwen3-8B' | Out-Null
# Download: Uses the selected local LLM directory, for example models/llm/Qwen3-8B.
# License: Serving framework license differs from model license; confirm both.
# Verify: Start an OpenAI-compatible local server and use the HTTP translation profile.

# translation / SGLang
uv pip install sglang
New-Item -ItemType Directory -Force -Path 'models\llm\Qwen3-8B' | Out-Null
# Download: Uses the selected local LLM directory, for example models/llm/Qwen3-8B.
# License: Serving framework license differs from model license; confirm both.
# Verify: Start an OpenAI-compatible local server and use the HTTP translation profile.
