$ErrorActionPreference = "Stop"

# Generated by Intelligent Voice Over.
# 确认模型许可证后再下载或使用；不同模型许可证独立于本项目代码许可证。
# 不要提交 models/、真实视频、生成音频、API key、HF_TOKEN 或其他密钥到 Git。
# 如需访问 Hugging Face 受限模型，请先运行 huggingface-cli login；不要把 token 写入脚本。
# Do not commit model weights, API tokens, HF_TOKEN, or generated media to Git.
# Review each model license before commercial use or redistribution.

# asr / faster-whisper
uv pip install faster-whisper
New-Item -ItemType Directory -Force -Path 'models\asr\faster-whisper-large-v3' | Out-Null
huggingface-cli download Systran/faster-whisper-large-v3 --local-dir 'models\asr\faster-whisper-large-v3'
# License: MIT package; confirm the selected Whisper checkpoint license.
# Verify: uv run ivo model smoke-asr --dry-run

# separation / demucs
# Manual install: uv sync --extra local-separation
New-Item -ItemType Directory -Force -Path 'models\separation\demucs' | Out-Null
# Download: Demucs downloads named checkpoints on first use.
# License: MIT; confirm checkpoint terms before distribution.
# Verify: uv run python examples/local_commands/demucs_separate.py --help

# diarization / pyannote.audio
# Manual install: install pyannote.audio>=4,<5 in an isolated .venv-pyannote environment; it conflicts with F5-TTS numpy constraints in the main venv
New-Item -ItemType Directory -Force -Path 'models\diarization\pyannote-community-1' | Out-Null
huggingface-cli download pyannote/speaker-diarization-community-1 --local-dir 'models\diarization\pyannote-community-1'
# License: Requires Hugging Face login and accepted model terms; keep HF_TOKEN out of Git.
# Verify: .venv-pyannote/Scripts/python.exe examples/local_commands/pyannote_diarization.py --help

# tts / CosyVoice
# Manual install: uv sync --extra local-tts-cosyvoice, then install CosyVoice from https://github.com/FunAudioLLM/CosyVoice
New-Item -ItemType Directory -Force -Path 'models\tts\Fun-CosyVoice3-0.5B' | Out-Null
huggingface-cli download FunAudioLLM/Fun-CosyVoice3-0.5B-2512 --local-dir 'models\tts\Fun-CosyVoice3-0.5B'
# License: Fun-CosyVoice3 model card currently lists Apache-2.0; re-check before use.
# Verify: uv run python examples/local_commands/cosyvoice_tts.py --help

# tts / f5_tts
# Manual install: uv sync --extra local-tts-f5
New-Item -ItemType Directory -Force -Path 'models\tts\F5-TTS' | Out-Null
huggingface-cli download SWivid/F5-TTS --local-dir 'models\tts\F5-TTS'
# License: Code is MIT; pretrained checkpoints are CC-BY-NC.
# Verify: uv run f5-tts_infer-cli --help

# translation / Qwen local LLM
uv pip install transformers accelerate
New-Item -ItemType Directory -Force -Path 'models\llm\Qwen3-8B' | Out-Null
huggingface-cli download Qwen/Qwen3-8B --local-dir 'models\llm\Qwen3-8B'
# License: Confirm the selected Qwen model license before redistribution or commercial use.
# Verify: Run Qwen through vLLM/SGLang/OpenAI-compatible HTTP profile first.

# translation / vLLM
# Manual install: install vLLM in a supported serving environment
New-Item -ItemType Directory -Force -Path 'models\llm\Qwen3-8B' | Out-Null
# Download: Uses the selected local LLM directory, for example models/llm/Qwen3-8B.
# License: Serving framework license differs from model license; confirm both.
# Verify: Start an OpenAI-compatible local server and use the HTTP translation profile.

# translation / SGLang
# Manual install: install SGLang in a supported serving environment
New-Item -ItemType Directory -Force -Path 'models\llm\Qwen3-8B' | Out-Null
# Download: Uses the selected local LLM directory, for example models/llm/Qwen3-8B.
# License: Serving framework license differs from model license; confirm both.
# Verify: Start an OpenAI-compatible local server and use the HTTP translation profile.
